# Default initial positions for six_dof_arm's ros2_control fake system

initial_positions:
  arm_1_to_arm_2: 0
  arm_2_to_arm_3: 0
  arm_3_to_arm_4: 0
  arm_4_to_arm_5: 0
  arm_5_to_arm_6: 0
  base_to_arm_1: 0